# Generated by Django 2.1.2 on 2018-10-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0002_product_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Saudi Arabia', max_length=255),
            preserve_default=False,
        ),
    ]
