# Generated by Django 2.1 on 2018-08-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0002_auto_20180815_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub Categorie'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='main_category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='main_category',
            field=models.ManyToManyField(to='ssw.Category'),
        ),
    ]
