# Generated by Django 2.1.2 on 2018-10-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0003_address_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earning',
            old_name='orderItem',
            new_name='order_item',
        ),
    ]
