# Generated by Django 2.1 on 2018-08-17 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0004_auto_20180817_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='owner',
        ),
        migrations.AddField(
            model_name='sowarstockuser',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ssw.Address'),
        ),
    ]
