# Generated by Django 2.1.2 on 2018-10-27 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0005_auto_20181027_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='earning',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ssw.Earning'),
        ),
    ]
