# Generated by Django 2.1.2 on 2018-10-29 03:34

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0006_auto_20181027_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='watermark',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='products/watermarked/'),
        ),
    ]
