# Generated by Django 2.1 on 2018-08-20 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0006_auto_20180817_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=255)),
                ('system_generated', models.BooleanField(default=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sowarstockuser',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='sowarstockuser',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ar', 'Arabic')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sowarstockuser',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ssw.Address'),
        ),
        migrations.AlterField(
            model_name='sowarstockuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_for', to='ssw.SowarStockUser'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_from', to='ssw.SowarStockUser'),
        ),
    ]
