# Generated by Django 2.1.2 on 2018-10-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0007_product_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
