# Generated by Django 2.1.2 on 2018-10-30 20:52

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0008_contributor_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='file_type',
            field=models.CharField(choices=[('jpeg', 'JPEG'), ('eps', 'EPS')], default='jpeg', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
