# Generated by Django 2.1 on 2018-08-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0009_auto_20180820_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='photo_id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sowarstockuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
