# Generated by Django 2.1.2 on 2018-11-01 16:37

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0009_auto_20181030_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eps_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
