# Generated by Django 2.1 on 2018-08-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0010_auto_20180820_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='system_generated',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('success', 'Success'), ('error', 'Error')], default='neutral', max_length=255),
        ),
    ]
