# Generated by Django 2.1 on 2018-08-23 02:21

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0011_auto_20180821_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('sowarstockuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ssw.SowarStockUser')),
            ],
            options={
                'verbose_name': 'Client User',
            },
            bases=('ssw.sowarstockuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssw.SowarStockUser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ssw.Product')),
            ],
        ),
    ]
