# Generated by Django 2.1 on 2018-08-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0012_client_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
