# Generated by Django 2.1.2 on 2018-11-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0013_auto_20181104_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowarstockuser',
            name='country_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
