# Generated by Django 2.1 on 2018-08-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0014_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='body',
            field=models.CharField(default='pending_approval', max_length=255),
        ),
    ]
