# Generated by Django 2.1.2 on 2018-11-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0014_auto_20181105_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='contributor',
            name='iban',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='paypal_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='preferred_payment_method',
            field=models.CharField(blank=True, choices=[('direct_bank_deposit', 'Direct Bank Deposit'), ('western_union', 'Western Union'), ('paypal', 'Paypal')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='western_union_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
