# Generated by Django 2.1 on 2018-09-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0016_faqpersonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssw.Contributor')),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_for',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_from',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('pending_admin_approval', 'Pending Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=255),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddField(
            model_name='collection',
            name='product',
            field=models.ManyToManyField(to='ssw.Product'),
        ),
    ]
