# Generated by Django 2.1.2 on 2018-11-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0016_auto_20181108_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='completed_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='read_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='read_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
