# Generated by Django 2.1.2 on 2018-11-10 14:00

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0017_auto_20181108_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='sample-products/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssw.Contributor')),
            ],
        ),
    ]
