# Generated by Django 2.1 on 2018-09-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0017_auto_20180906_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='product',
            new_name='products',
        ),
    ]
