# Generated by Django 2.1 on 2018-09-13 01:41

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0018_auto_20180907_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=django_mysql.models.SetTextField(models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='sowarstockuser',
            name='type',
            field=models.CharField(choices=[('contributor', 'Contributor'), ('client', 'Client'), ('admin', 'Admin'), ('image_reviewer', 'Image Reviewer'), ('financial_admin', 'Financial Admin')], max_length=255),
        ),
    ]
