# Generated by Django 2.1.2 on 2018-11-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0019_auto_20181112_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='featured/'),
        ),
        migrations.AlterField(
            model_name='sampleproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sample-products/'),
        ),
    ]
