# Generated by Django 2.1 on 2018-09-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0019_auto_20180913_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.CharField(max_length=255),
        ),
    ]
