# Generated by Django 2.1.2 on 2018-11-12 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0020_auto_20181112_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssw.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='description goes here'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssw.SubCategory'),
        ),
    ]
