# Generated by Django 2.1 on 2018-09-17 19:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0023_shoppingcart_shoppingcartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='owner',
        ),
        migrations.AddField(
            model_name='client',
            name='shopping_cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ssw.ShoppingCart'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
    ]
