# Generated by Django 2.1.2 on 2018-11-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0023_auto_20181114_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleproduct',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='sample-products/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='sampleproduct',
            name='image',
            field=models.ImageField(upload_to='sample-products/'),
        ),
    ]
