# Generated by Django 2.1.2 on 2018-11-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0024_auto_20181114_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='adult_content',
            field=models.BooleanField(default=False),
        ),
    ]
