# Generated by Django 2.1 on 2018-09-17 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0024_auto_20180917_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='shopping_cart',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ssw.Client'),
            preserve_default=False,
        ),
    ]
