# Generated by Django 2.1 on 2018-09-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0025_auto_20180917_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='legal/')),
            ],
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='description_about_artist',
        ),
        migrations.AddField(
            model_name='sowarstockuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
