# Generated by Django 2.1 on 2018-09-25 15:31

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0026_auto_20180924_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
