# Generated by Django 2.1.2 on 2018-11-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0027_auto_20181115_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowarstockuser',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
