# Generated by Django 2.1 on 2018-09-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0028_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
