# Generated by Django 2.1 on 2018-09-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0029_order_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='status',
            field=models.CharField(choices=[('in_cart', 'In Cart'), ('removed', 'Removed')], default='in_cart', max_length=255),
        ),
    ]
