# Generated by Django 2.1 on 2018-09-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0030_shoppingcartitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='license_type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shopping_cart_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shopping_cart_item', to='ssw.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='ssw.Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='ssw.Product'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='status',
            field=models.CharField(choices=[('in_cart', 'In Cart'), ('removed', 'Removed'), ('purchased', 'Purchased')], default='in_cart', max_length=255),
        ),
    ]
