# Generated by Django 2.1.2 on 2018-11-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0030_auto_20181116_0815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchKeywords',
            new_name='SearchKeywordSynonyms',
        ),
    ]
