# Generated by Django 2.1.2 on 2018-11-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0032_searchkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
