# Generated by Django 2.1 on 2018-09-26 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0032_auto_20180926_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='shopping_cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_cart_item', to='ssw.ShoppingCartItem'),
        ),
    ]
