# Generated by Django 2.1.2 on 2018-10-05 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0033_auto_20180926_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowarstockuser',
            name='email_verfification_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='ssw.Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='public_id',
            field=models.IntegerField(unique=True),
        ),
    ]
