# Generated by Django 2.1.2 on 2018-11-24 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0033_contributor_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='earning',
        ),
        migrations.AddField(
            model_name='earning',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ssw.Payment'),
        ),
    ]
