# Generated by Django 2.1.2 on 2018-11-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0034_auto_20181124_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='type',
            field=models.CharField(choices=[('id', 'ID'), ('delete', 'Delete')], default='id', max_length=255),
        ),
    ]
