# Generated by Django 2.1.2 on 2018-10-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0034_auto_20181005_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sowarstockuser',
            old_name='email_verfification_code',
            new_name='email_verification_code',
        ),
    ]
