# Generated by Django 2.1.2 on 2018-10-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0035_auto_20181005_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowarstockuser',
            name='forgot_password_status',
            field=models.CharField(choices=[('none', 'None'), ('not_used', 'Not Used'), ('used', 'Used')], default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='sowarstockuser',
            name='forgot_password_verification',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
