# Generated by Django 2.1.2 on 2018-11-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0035_userrequest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='bank_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='file_type',
            field=models.CharField(choices=[('jpeg/tiff', 'JPEG/TIFF'), ('eps', 'EPS')], default='jpeg/tiff', max_length=255),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='type',
            field=models.CharField(choices=[('id', 'ID'), ('delete', 'Delete Account')], default='id', max_length=255),
        ),
    ]
