# Generated by Django 2.1.2 on 2018-11-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0036_auto_20181126_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail2',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnails/'),
        ),
    ]
