# Generated by Django 2.1.2 on 2018-11-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0037_product_thumbnail2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail2',
        ),
    ]
