# Generated by Django 2.1.2 on 2018-11-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0038_remove_product_thumbnail2'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
