# Generated by Django 2.1.2 on 2018-12-01 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0039_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviewer', to='ssw.SowarStockUser'),
        ),
        migrations.AlterField(
            model_name='faqpersonal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_personal_owner', to='ssw.Contributor'),
        ),
        migrations.AlterField(
            model_name='faqpersonal',
            name='replier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faq_personal_replier', to='ssw.SowarStockUser'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_owner', to='ssw.Contributor'),
        ),
    ]
