# Generated by Django 2.1.2 on 2018-12-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0040_auto_20181201_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watermark', models.ImageField(blank=True, null=True, upload_to='watermarks/')),
                ('exclusive_percentage', models.IntegerField()),
                ('non_exclusive_percentage', models.IntegerField()),
                ('paypal_testing', models.BooleanField(default=True)),
            ],
        ),
    ]
