# Generated by Django 2.1.2 on 2018-12-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0041_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='type',
            field=models.CharField(choices=[('new_account', 'New Account'), ('delete_account', 'Delete Account')], default='id', max_length=255),
        ),
    ]
