# Generated by Django 2.1.2 on 2018-12-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0042_auto_20181203_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleproduct',
            name='viewed_by_admin',
        ),
        migrations.RemoveField(
            model_name='sampleproduct',
            name='viewed_by_reviewer',
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='type',
            field=models.CharField(choices=[('new_contributor', 'New Contributor'), ('delete_account', 'Delete Account')], default='id', max_length=255),
        ),
    ]
