# Generated by Django 2.1.2 on 2018-12-09 02:17

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0043_auto_20181205_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='bank_owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='residency_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='bank_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='type',
            field=models.CharField(choices=[('new_contributor', 'New Contributor'), ('delete_account', 'Delete Account')], default='new_contributor', max_length=255),
        ),
    ]
