# Generated by Django 2.1.2 on 2018-12-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0044_auto_20181209_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='editorial',
            field=models.BooleanField(default=False),
        ),
    ]
