# Generated by Django 2.1.2 on 2018-12-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0046_auto_20181214_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowarstockuser',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
