# Generated by Django 2.1.2 on 2018-12-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0047_sowarstockuser_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleproduct',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sampleproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sample-products/'),
        ),
    ]
