# Generated by Django 2.1.2 on 2018-12-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0048_auto_20181219_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='photo_id_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='document_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='file_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sowarstockuser',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
