# Generated by Django 2.1.2 on 2018-12-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0049_auto_20181220_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowarstockuser',
            name='profile_image_crop',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/crop/'),
        ),
    ]
