# Generated by Django 2.1.2 on 2018-12-21 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0050_sowarstockuser_profile_image_crop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ssw.Contributor'),
        ),
    ]
