# Generated by Django 2.1.2 on 2018-12-21 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0051_auto_20181221_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssw.Contributor'),
        ),
    ]
