# Generated by Django 2.1.2 on 2018-12-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0054_systemlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemlog',
            old_name='description',
            new_name='long_description',
        ),
    ]
