# Generated by Django 2.1.2 on 2019-01-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0056_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='sample_portfolio_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
