# Generated by Django 2.1.2 on 2019-01-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0057_contributor_sample_portfolio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='sample_portfolio_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
