# Generated by Django 2.1.2 on 2019-01-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0059_auto_20190102_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='rejection_note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
