# Generated by Django 2.1.2 on 2019-01-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0060_userrequest_rejection_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
