# Generated by Django 2.1.2 on 2019-01-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssw', '0061_auto_20190112_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sowarstockuser',
            name='type',
            field=models.CharField(choices=[('contributor', 'Contributor'), ('client', 'Client'), ('admin', 'Admin'), ('image_reviewer', 'Image Reviewer'), ('financial_admin', 'Financial Admin'), ('customer_rep', 'Customer Representative')], max_length=255),
        ),
    ]
